### ISSUE TITLE
[B-INFO] 회원가입 페이지 최종 가입하기 오류

### ISSUE THREAD

**Issue by KRimwoo** [peer-42seoul/Peer-Frontend#194]
#### 문제 상황
마지막 회원가입 단계에서 가입하기 요청시 400 에러 발생

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : Chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 상태 아님

#### 재현 절차
이메일 코드 인증 완료. 닉네임 중복 확인 완료 후 가입하기 버튼 클릭.

#### 예상 결과
'회원 가입이 완료되었습니다' 메세지 이후 메인페이지로 이동

#### 실제 결과
400 Bad Request 응답 받음. '유효하지 않은 회원가입 정보입니다' 메세지 표시

#### 심각도
중

**Comment by heehoh** [comment]
회원가입 됩니다!
