### ISSUE TITLE
[PUBLIC] 로그인 없이 axiosWithAuth 사용한 request 발생 시 alert가 무한히 뜨는 문제

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Frontend#195]
#### 문제 상황
![axios 로그인 없이 401 발생 시 alert가 무한정 발생하는 문제](https://github.com/peer-42seoul/Peer-Frontend/assets/91731260/3bfc0bde-24ef-4759-a98a-e05dd8b0d64f)

로그인 없이 axiosWithAuth 사용한 request 발생 시 라우팅이 안되고 alert가 무한히 뜨고 있습니다. 

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인을 하지 않은 상태

#### 재현 절차
로그인을 하지 않은 상태에서 내 프로필로 들어가면 발생합니다.

#### 예상 결과
로그인 페이지로 라우팅

#### 실제 결과
다시 로그인 해달라는 alert만 무한히 발생

#### 심각도
상

**Comment by SaltySalt77** [comment]
추가 확인 사항 : 해당 문제사항이 프로필 조회하기 api와 살짝 맞물려있는 것으로 추정됩니다. 다음 링크 [참고](https://github.com/peer-42seoul/Peer-Backend/issues/246)

토큰이 요구되는 api를 사용하는 다른 페이지에서도 확인이 필요합니다.

**Comment by KRimwoo** [comment]
my-page에서 axiosInstance를 일반 axios로 바꾸어도 페이지 렌더링 자체도 여러번 되는 것 같고 (SubNavBar의 콘솔이 여러번 찍힘) get요청도 연속적으로 이루어지는 것 같은데 이건 뭐 때문일까요..?

**Comment by SaltySalt77** [comment]
profile에서 get 요청이 계속 발생하는 것은 api response body가 달라서 다시 swr에서 요청 보내는 것으로 추정됩니다(................)
