### ISSUE TITLE
[B-INFO] 회원가입시, API 문서와 실제 필드 명이 다름

### ISSUE THREAD

**Issue by juhyeonlee134** [peer-42seoul/Peer-Frontend#198]
#### 문제 상황
<img width="192" alt="스크린샷 2023-11-02 오후 7 29 17" src="https://github.com/peer-42seoul/Peer-Frontend/assets/76419137/4690e9a6-d394-4a96-9a51-2c84d878ceca">

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
회원정보가 없는 상태에서 회원가입을 진행

#### 재현 절차
이메일 인증 통과, 닉네임 중복 체크 통과 이후 최종적으로 가입 하기 진행

#### 예상 결과
가입이 되어야 함

#### 실제 결과
"유효하지 않은 회원정보입니다"라는 창이 뜨면서 가입이 되지 않음.
실제 전달되는 payload 확인 결과, 필드 명이 달라서 나타나는 문제로 확인. (nickName -> nickname)

#### 심각도
상

**Comment by heehoh** [comment]
해결했습니다!
