### ISSUE TITLE
[논의] 팀 설정페이지에서 모집글수정페이지로 넘어갈때 해당 글의 id를 넘겨주어야합니다!

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#206]
팀 설정페이지에서 모집글수정페이지로 넘어갈때 해당 글의 id를 넘겨주어야합니다!
왜냐하면, 모집글 수정페이지로 오게되면 수정한 정보를 API로 백엔드로 넘겨줄때 해당글의 recruit_id 를 같이 전달해줘야하기 때문입니다. 지금은 이 값이 없어서 처리를 못하고 있어용

어떻게 해야할까요?

**Comment by SaltySalt77** [comment]
id의 용도를 알 수 있을까요?

**Comment by joonseong11** [comment]
잠시만요 전에 다르이유로 필요했엇는데 지금 필요한지 다시 검토해보고 진행해야겠어요

**Comment by joonseong11** [comment]
@SaltySalt77 위의 본문에 추가되었습니다!

**Comment by SaltySalt77** [comment]
<img width="1440" alt="스크린샷 2023-11-03 오후 12 29 03" src="https://github.com/peer-42seoul/Peer-Frontend/assets/91731260/e244adf9-0f60-4da2-9b0a-6bcdc0e1602d">
이 파일에 해당하는 내용인 것 같은데, 파일 구조를 보면 [id]값을 받는데, `CreateTeam`컴포넌트에서는 해당 id값을 받지 않고 있네요. 
[여기](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes)를 참고해보시는 게 좋을 것 같아요

**Comment by joonseong11** [comment]
넵넵 감사합니당
