### ISSUE TITLE
[C-SRC-23] 지난 검색어 에러

### ISSUE THREAD

**Issue by sinryuji** [peer-42seoul/Peer-Frontend#210]
#### 문제 상황
- 최대 5개 표시라고 하셨는데 4개만 표시됨
- 삭제가 안됨
- 가장 최근에 검색한 순서대로 표시되지 않고 검색어 자체로 정렬되는 것 같음

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
없음

#### 재현 절차
검색 버튼 클릭 - 검색어 입력 - 검색

#### 예상 결과
- 지난 검색어가 5개가 떠야함
- 삭제 버튼 클릭 시 삭제가 되어야 함
- 가장 최근의 검색어가 맨 위에 뜨고 오래된 순서대로 밀려 없어져야함

#### 실제 결과
- 지난 검색어가 4개만 뜸
- 삭제 버튼을 눌러도 다시 검색창 띄웠을때 삭제한 검색어가 남아있음
- 지난 검색어 순서가 검색어로 정렬되어 표현 됨

#### 심각도
하

**Comment by HiHoi** [comment]
작업 진행하겠습니다.

**Comment by HiHoi** [comment]
@sinryuji 혹시 해결된 이슈로 넘겨도 될까요?

**Comment by sinryuji** [comment]
@HiHoi 넵!
