### ISSUE TITLE
[C-MYPAGE] 쪽지 상대방 검색 api 주소 에러

### ISSUE THREAD

**Issue by perman0519** [peer-42seoul/Peer-Frontend#213]
#### 문제 상황
<img width="1680" alt="스크린샷 2023-11-03 오후 2 54 39" src="https://github.com/peer-42seoul/Peer-Frontend/assets/102403228/51e5349c-56fa-4e6a-8c0a-9bc23bde9275">

쪽지 사용자 검색 시 에러 발생
#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 후

#### 재현 절차
쪽지 페이지에 가서 상대방 사용자를 검색한다

#### 예상 결과
찾는 사용자가 나와야 함

#### 실제 결과
존재하지 않는 사람입니다

#### 심각도
상

**Comment by yoouyeon** [comment]
쪽지쪽 api 연결은 아직 머지가 안되어서 테스트가 안되는 상황입니다 ㅠㅅㅠ
