### ISSUE TITLE
[C-MYPAGE-49~54]  팀 리스트 요청 url 최신화

### ISSUE THREAD

**Issue by wochae** [peer-42seoul/Peer-Frontend#221]
#### 문제 상황
API 명세서와 다른 요청을 보내는 상태

#### 테스트 환경

- OS(mac / ipad / android...) :  mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 된 상태
#### 재현 절차
프론트 백 모두 로컬로 서버를 올리고 로그인 한 상태에서  팀페이지 ( ~/team-list ) 페이지로 이동 시,
- 프론트 코드
![image](https://github.com/peer-42seoul/Peer-Frontend/assets/101040879/c9ab802b-1527-4adb-af1d-891d3800d88f)
- 브라우저 콘솔
![image](https://github.com/peer-42seoul/Peer-Frontend/assets/101040879/1d9a90a5-3cc2-4638-9e1a-c2a5e31f70ae)
- 명세서
<img width="403" alt="image" src="https://github.com/peer-42seoul/Peer-Frontend/assets/101040879/0c0c867f-ae63-42fe-b353-c3eb68a6803f">

#### 예상 결과
명세서 반환값
#### 실제 결과
401 Unauthorize.

list/{userId} -> list?teamStatus= 로 변경,
로컬 스토리지 토큰 사용
#### 심각도
하

**Comment by HiHoi** [comment]
@wochae 1차 변경했습니다. 확인해주세요

**Comment by wochae** [comment]
![image](https://github.com/peer-42seoul/Peer-Frontend/assets/101040879/09943db3-6bd8-476e-8cd6-5e7405979477)
수정 확인

![image](https://github.com/peer-42seoul/Peer-Frontend/assets/101040879/dbf8615d-a0aa-4b08-afb2-30629146f4d0)
아직 teamStatus가 encoded url 로 전송되고 있음.

![image](https://github.com/peer-42seoul/Peer-Frontend/assets/101040879/f795f57c-0bd9-46bd-b86b-7445aa801447)
근데 이것보다 요청이 Unauthorized 되고 있어서 백 서버에 로그가 남지 않고 있는 상황

**Comment by HiHoi** [comment]
@wochae 내일 직접 나가서 어떤 점이 문제일지 파악하고 바로 고치겠습니다.

**Comment by HiHoi** [comment]
https://github.com/peer-42seoul/Peer-Frontend/pull/280
