### ISSUE TITLE
[C-SIGN-01] 로그인 된 상태에서 프로필 이미지를 누르면 다시 로그인 창으로 이동

### ISSUE THREAD

**Issue by sinryuji** [peer-42seoul/Peer-Frontend#238]
#### 문제 상황
로그인 된 상태에서 프로필 이미지를 누르면 다시 로그인 창으로 이동

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
- 로그인

#### 재현 절차
- 로그인 -> 홈에서 프로필 이미지 클릭

#### 예상 결과
- 마이페이지 이동

#### 실제 결과
- 로그인 페이지 이동

#### 심각도
중

**Comment by KRimwoo** [comment]
저는 왜 잘 될까유....

**Comment by sinryuji** [comment]
죄송해유
