### ISSUE TITLE
[J-TB] 로그인 없이 새글쓰기를 누르면 페이지로 넘어가짐 

### ISSUE THREAD

**Issue by perman0519** [peer-42seoul/Peer-Frontend#255]
#### 문제 상황
로그인을 하지 않고 글쓰기로 넘어가는지 확인
<img width="1800" alt="스크린샷 2023-11-10 오후 2 54 44" src="https://github.com/peer-42seoul/Peer-Frontend/assets/102403228/b6bb97b0-c6fc-4604-a45e-e7af25f422b9">

#### 테스트 환경

- OS(mac / ipad / android...) :mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 x
#### 재현 절차
잘 넘어가짐
#### 예상 결과
넘어가면 안되고 로그인 페이지로 이동되어야 함
#### 실제 결과
글쓰기 페이지로 간다
#### 심각도
상

**Comment by joonseong11** [comment]
다음 pr 반영예정
