### ISSUE TITLE
[C-MAIN] 필터 초기화 기능 이상

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#256]
#### 문제 상황
<img width="731" alt="Screenshot 2023-11-10 at 3 05 23 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/dae93086-1767-4a49-b268-81c14f9695d5">

초기화 버튼을 누르면 텍스트 필드는 초기화 기능 이상없으나, 
체크박스로 된 작업유형, 작업단계는 초기화 되지 않음.
#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인안함

**Comment by hyeon81** [comment]
해결되었습니다 https://github.com/peer-42seoul/Peer-Frontend/pull/289

**Comment by hyeon81** [comment]
해결되었습니다 https://github.com/peer-42seoul/Peer-Frontend/pull/289
