### ISSUE TITLE
[C-TB] 네비게이션바에서 팀페이지를 선택하면 쇼케이스가 활성화됨

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#257]
#### 문제 상황
<img width="1261" alt="Screenshot 2023-11-10 at 3 09 39 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/bf1fb709-19cf-4116-ab63-eb71976e635f">

네비게이션바에서 팀페이지를 선택하면 쇼케이스가 활성화됨

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : safari

#### 사전 조건 (ex. 로그인 여부)
로그인 안함

#### 재현 절차
네비바에서 팀페이지 선택

#### 예상 결과
팀페이지가 활성화 되어야하는데

#### 실제 결과
쇼케이스가 활성화됨

**Comment by hyeon81** [comment]
수정되었습니다. 관련 pr https://github.com/peer-42seoul/Peer-Frontend/pull/289
