### ISSUE TITLE
[C-MYPAGE] 프로필에서 링크수정 반영안됨

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#258]
#### 문제 상황
프론트에서는 링크등록 성공 알림이 뜨긴하지만
링크 등록해도 반영이 안됨.

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : safari

#### 사전 조건 (ex. 로그인 여부)
로그인됨

#### 재현 절차
프로필에서 링크 등록

**Comment by SaltySalt77** [comment]
해당 버그 프론트의 문제로 판단되어 pr 올릴 예정입니다.

**Comment by SaltySalt77** [comment]
@juhyeonlee134 
[프로필 정보 조회](https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=39699848)에는 링크 주소가 'link'로 되어있고,
[프로필 링크 수정](https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=39700780)에는 링크 주소가 'linkUrl'로 되어있어서 통일이 필요합니다 :(

**Comment by SaltySalt77** [comment]
해결되어 닫겠습니다~
