### ISSUE TITLE
[C-CAN] 계정 삭제 안됨.

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#260]
#### 문제 상황
<img width="1058" alt="Screenshot 2023-11-10 at 3 30 23 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/d2733175-1781-460a-a6bf-7e3e2ecaf329">
계정삭제를 누르고 비밀번호를 맞게 입력해도 계정삭제가 안되고, 로그인페이지로 돌아감. 
다시 로그인하면 로그인됨.

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : safari

#### 사전 조건 (ex. 로그인 여부)
로그인됨

**Comment by heehoh** [comment]
수정했습니다!
