### ISSUE TITLE
[C-MYPAGE] 알림 키워드 등록 버튼 없음.

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#261]
#### 문제 상황
<img width="1215" alt="Screenshot 2023-11-10 at 3 38 15 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/a197afe1-f5a4-4433-aa8c-a3a50f68e7ac">

알림키워드 등록 버튼이 없음.

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by SaltySalt77** [comment]
해당 문제는 최신 코드가 사이트에 반영이 안되던 문제였으므로 클로즈 처리하겠습니다.
