### ISSUE TITLE
[C-MYPAGE-49~54] 401

### ISSUE THREAD

**Issue by perman0519** [peer-42seoul/Peer-Frontend#263]
#### 문제 상황
팀 리스트 페이지 401 에러
<img width="1800" alt="스크린샷 2023-11-10 오후 3 43 48" src="https://github.com/peer-42seoul/Peer-Frontend/assets/102403228/5673c628-aacb-4523-ae19-98c2dd309af6">

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 해야됨
#### 재현 절차
팀페이지로 간다
#### 예상 결과
속한 팀 리스트가 보여야 함
#### 실제 결과
401
#### 심각도
중

**Comment by HiHoi** [comment]
바로 해결했습니다. 추가 작업 이후 PR 올리겠습니다.

**Comment by HiHoi** [comment]
https://github.com/peer-42seoul/Peer-Frontend/pull/280
