### ISSUE TITLE
[/api/v1/recriut/interview/{post_id}] 모집글 페이지 지원하기 오류 404

### ISSUE THREAD

**Issue by perman0519** [peer-42seoul/Peer-Frontend#266]
#### 문제 상황
<img width="1800" alt="image" src="https://github.com/peer-42seoul/Peer-Frontend/assets/102403228/0331e31f-c00c-4df4-a93a-373d69051321">

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 예상 결과
등록되어야 함
#### 실제 결과
404
#### 심각도
상

**Comment by hyeon81** [comment]
url 경로가 잘못되어 일어났던 일입니다 지금은 200뜹니다!
