### ISSUE TITLE
[C-MYPAGE-37 ~ 38] 관심 리스트 페이지에서 관심글로 안넘어가지는 현상

### ISSUE THREAD

**Issue by perman0519** [peer-42seoul/Peer-Frontend#274]
#### 문제 상황
<img width="889" alt="스크린샷 2023-11-10 오후 5 36 08" src="https://github.com/peer-42seoul/Peer-Frontend/assets/102403228/97587a6e-4ba2-46c3-9628-562c0c3492ee">
<img width="887" alt="스크린샷 2023-11-10 오후 5 36 21" src="https://github.com/peer-42seoul/Peer-Frontend/assets/102403228/a475e543-4d1a-408b-91ac-94de8be7fe0c">
관심 리스트 페이지에서 관심글로 안넘어가지는 현상

#### 테스트 환경
- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 재현 절차
관심리스트 페이지에서 관심글을 클릭

#### 예상 결과
메인페이지 처럼 잘 들어가져야 함

#### 실제 결과
안들어가짐
그리고 하트도 색 안칠해져 있습니다~

#### 심각도
상

**Comment by SaltySalt77** [comment]
처리 완료되어 close하겠습니다.
