### ISSUE TITLE
[C-TB-00] 탭바가 모바일 화면 끝에 붙어있지 않은 현상

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Frontend#275]
#### 문제 상황
탭바가 모바일 화면 끝에 붙어있지 않음
![20231110_184338.gif](https://github.com/peer-42seoul/Peer-Frontend/assets/91731260/856a7d5b-2c71-45c4-8d94-d0d0384e13a4)

#### 테스트 환경

- OS(mac / ipad / android...) : android
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
관련 없음

#### 재현 절차
페이지 접근

#### 예상 결과
사이트 접근시 아래에 탭바가 바로 보인다

#### 실제 결과
바로 보이지 않고, 스크롤을 끝까지 내려야 뜬다.

#### 심각도
하

**Comment by hyeon81** [comment]
수정되었습니ㅏㄷ!
