### ISSUE TITLE
[C-MYPAGE-37] 관심 리스트에서 하트가 안켜져있고 이걸 키면 관심페이지에서 사라짐 거꾸로됨

### ISSUE THREAD

**Issue by perman0519** [peer-42seoul/Peer-Frontend#281]
#### 문제 상황
<img width="1800" alt="스크린샷 2023-11-10 오후 8 54 19" src="https://github.com/peer-42seoul/Peer-Frontend/assets/102403228/372c3ce1-ebec-40c3-b2cd-5fad0106c61d"
<img width="1800" alt="스크린샷 2023-11-10 오후 8 54 17" src="https://github.com/peer-42seoul/Peer-Frontend/assets/102403228/1f92291c-3cda-40c2-bde4-8c0c99a96b62">
>

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 :chrome

#### 사전 조건 (ex. 로그인 여부)
로그인하고 관심리스트를 추가한 상태
#### 예상 결과
켜진 하트를 꺼야됨
#### 실제 결과
꺼진 하트가 켜지고 삭제됨 
#### 심각도
상?

**Comment by SaltySalt77** [comment]
해당 버그 원인 : response의 body와 Maincard 컴포넌트간 타입이 달라서 발생한 현상임
수정 예정

**Comment by SaltySalt77** [comment]
처리 완료되어 close 처리하겠습니다
