### ISSUE TITLE
[A-JOI, B-INFO] 로그인 상태에서 개인정보보호동의, 회원가입 페이지 진입가능

### ISSUE THREAD

**Issue by KRimwoo** [peer-42seoul/Peer-Frontend#292]
#### 문제 상황
로그인 상태에서 해당 페이지로 진입하면 회원가입을 진행할 수 있음

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 x/o 두 조건 전부

#### 재현 절차
로그아웃 상태에서 회원가입 진입
로그인 상태에서 /privacy, /signup으로 진입

#### 예상 결과
로그인 상태에서는 홈으로 다시 리다이렉션됨

#### 실제 결과
로그인 상태에서 회원가입을 진행할 수 있음

#### 심각도
중

**Comment by heehoh** [comment]
전역 상태관리로 로그인 상태인지 아닌지 확인해서 로그인 상태이면 router.replace를 사용해서 해결했습니다!
