### ISSUE TITLE
[C-MAIN] 메인페이지 모집글 리스트에서 하트 표시가 새로고침시 사라짐

### ISSUE THREAD

**Issue by sinryuji** [peer-42seoul/Peer-Frontend#295]
#### 문제 상황
메인페이지 모집글 리스트에서 하트 표시를 하면 클릭했을시에는 잘 표시됨.
마이페이지 관심 리스트에도 잘 표시됨.
그런데 다시 메인페이지로 돌아갈 시 하트 표시가 사라져있음.

#### 테스트 환경

- OS(mac / ipad / android...): mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인

#### 재현 절차
로그인 - 메인페이지에서 모집글 하트 클릭 - 마이페이지 관심 리스트에 잘 추가되었는지 확인 - 다시 메인페이지에 돌아와 하트 확인

#### 예상 결과
하트를 누른 모집글들에 하트가 잘 표시되어야 한다.

#### 실제 결과
내가 누른 하트 표시가 취소되어 있음

#### 심각도
중

**Comment by hyeon81** [comment]
https://github.com/peer-42seoul/Peer-Frontend/pull/367 에서 수정되었습니다
