### ISSUE TITLE
[C-MAIN] 작업유형을 여러개 선택 시 검색 결과 - 에러발생

### ISSUE THREAD

**Issue by KRimwoo** [peer-42seoul/Peer-Frontend#297]
#### 문제 상황
작업유형을 여러개 선택하면 결과로 에러가 발생함

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 x

#### 재현 절차
검색 세부옵션의 작업 유형을 여러개 선택

#### 예상 결과
혼합된 검색 결과 보여짐

#### 실제 결과
에러 발생 테스트가 보임

#### 심각도
중

**Comment by hyeon81** [comment]
백엔드 이슈로 해결되었습니다~ 관련 이슈 https://github.com/peer-42seoul/Peer-Backend/issues/338

**Comment by hyeon81** [comment]
백엔드 이슈 였고 지금은 해결되었습니다~ 관련 이슈 https://github.com/peer-42seoul/Peer-Backend/issues/338
