### ISSUE TITLE
[C-MYPAGE] 프로필 링크 수정 도중 계정 삭제됨

### ISSUE THREAD

**Issue by KRimwoo** [peer-42seoul/Peer-Frontend#298]
#### 문제 상황
프로필 링크 추가, 수정, 삭제 도중 계정이 삭제되어버리는 현상

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 상태

#### 재현 절차
마이페이지 링크에 데이터를 추가하고 수정, 삭제

#### 예상 결과
데이터가 업데이트 됨

#### 실제 결과
500번대 에러를 받고 계정이 삭제됨

#### 심각도
상

**Comment by SaltySalt77** [comment]
처리 완료되어 클로즈하겠습니다~
