### ISSUE TITLE
[J-TB] 모집글 뷰 페이지 지원하기 질문폼

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Frontend#316]
#### 문제 상황
에러에 대한 리스폰스가 부족합니다.

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 되어있는 상황

#### 재현 절차
1. 모집글로 접근하여 지원하기를 누른다.
2. 필수 질문란에 답변을 넣지 않고, 지원하기를 누른다.
3. 지원하겠냐는 모달에 지원하기를 누른다.

#### 예상 결과
잘못된 부분에 대한 리스폰스가 뜨고, 모달이 꺼진다. 텍스트 필드 등에 에러가 있다는 표기가 뜬다.

#### 실제 결과
폼에 문제가 있다는 토스트 등의 유저 리스폰스가 뜨지 않는다.
텍스트필드가 흰색으로 뜬다.
모달이 꺼지지 않는다.

#### 심각도
하

**Comment by hyeon81** [comment]
위 pr에서 수정되었습니다!
