### ISSUE TITLE
[J-TB] 모집글 뷰 페이지 버튼 z-index 잘못 설정된 문제

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Frontend#318]
#### 문제 상황
<img width="233" alt="스크린샷 2023-11-15 오후 4 28 05" src="https://github.com/peer-42seoul/Peer-Frontend/assets/91731260/fc856297-7835-430c-b867-0405943f9a83">

![J-TB 모집글 뷰 페이지 디자인 문제](https://github.com/peer-42seoul/Peer-Frontend/assets/91731260/ccbc0a19-1cd5-4d71-ac36-12bdd326066d)

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 된 상태

#### 재현 절차
스크롤을 올린다.

#### 예상 결과
스크롤을 올리면 내비게이션 바 아래로 버튼등 모집글 뷰 컴포넌트들이 들어간다.

#### 실제 결과
스크롤 올리면 특정 버튼 두 개가 내비게이션 바 위로 올라가버립니다.

#### 심각도
하

**Comment by hyeon81** [comment]
https://github.com/peer-42seoul/Peer-Frontend/pull/339에서 해결되었습니다
