### ISSUE TITLE
[D-TP] 팀페이지 Parallel Routes 제거

### ISSUE THREAD

**Issue by yoouyeon** [peer-42seoul/Peer-Frontend#356]
### 문제상황

현재 팀 페이지에는 Parallel Routes가 적용되어 있음.
Parallel Routes는 다른 route를 추가하기가 용이하고 성능 측면에서도 좋지만
공지사항, 게시판 페이지에서 페이지 path의 depth가 깊어졌을 때 뒤로가기, 다른 페이지 탭으로 이동 등의 작업에서 상태관리가 복잡해지는 문제가 생김
따라서 적용되어 있는 Parallel Routes를 제거하기로 함.

### 개선방향

- [x] main은 기존과 같이 teams/{id}로 path 설정
- [x] board, notice, setting은 teams/{id}/{각 위치}로 path 설정
- [x] 위 내용에 맞게 파일구조 변경

**Comment by HiHoi** [comment]
혹시 어디까지 진행되었을까요?

**Comment by yoouyeon** [comment]
@HiHoi 
지금까지 마이페이지의 파일 구조를 수정해야 한다고 착각하고 쪽지 부분이 완료되면 진행해야겠다고 생각하고 있었습니다.....
다시보니 팀페이지네요 😅
대부분 금방 할 수 있을 것 같아서 바로 시작하겠습니다!
공통 모달 작업하면서 팀페이지 부분 파일을 좀 건드려버려서 PR 올리는건 공통 모달 PR 머지되면 할 수 있을 것 같아요.
PR 올릴때 이 이슈 링크해서 머지하면서 같이 닫힐 수 있게 할게요!! 😁
