### ISSUE TITLE
[C-MYPAGE-30] 추가하려는 키워드 문자열이 기존에 등록한 키워드 문자열 안에 포함된 경우 중복처리 됨

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Frontend#378]
#### 문제 상황
추가하려는 키워드 문자열이 기존에 등록한 키워드 문자열 안에 포함된 경우 중복처리 됨
예를 들어 'test'를 등록하고, 'te'를 등록할 경우 400 에러가 발생합니다. ('te' 등록 이후, 'test' 등록시 에러 발생 안함)

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 필요.

#### 재현 절차
긴 문자열을 알림 키워드 추가에 등록한다.
해당 문자열 안에 포함된 문자열을 키워드 추가에 등록한다.

#### 예상 결과
둘 다 등록된다.

#### 실제 결과
400 에러가 발생하며, 중복된 알림 키워드라는 토스트 알림이 뜬다.

#### 심각도
중

**Comment by Paul2021-R** [comment]
흠 확인하고 수정해보겠습니다 ~

**Comment by Paul2021-R** [comment]
### 해결 및 업데이트 사항 
- 기존 로직에서 수정하여, 각 내부의 키워드를 정확하게 확인하는 방식으로 수정 
- Postman 등의 수동 접근을 대비하여 backend로직에서도 키워드 사이즈 제한 적용(최대 30자) 
- Postman 등의 수동 접근, 자동화로 키워드 무한 입력을 제거고자 최대 키워드 개수는 10개로 제한함
