### ISSUE TITLE
[BUG] 지원글에서 인터뷰 답변란이 안보임

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#459]
#### 문제 상황

지원 모집글에서 지원하기를 누르고 인터뷰에 답을 할 때 주관식 제외한 나머지 답의 형태가 안보임.
일단 제출은 가능한 상황

#### 테스트 환경

- OS(mac / ipad / android...) : macos
- 웹 브라우저 : 크롬

#### 사전 조건 (ex. 로그인 여부)

-  로그인 필수
- 지원하는 글에 인터뷰 글 필요
- 인터뷰의 종류는 주관식 제외한 나머지

#### 예상 결과

답변란이 보여서 알맞는 답변을 할 수 잇게

#### 실제 결과

안보임

#### 심각도

6 / 10

**Comment by hyeon81** [comment]
관련 이슈 https://github.com/peer-42seoul/Peer-Frontend/issues/480
