### ISSUE TITLE
[S-SC] 쇼케이스 링크 수정 시 값이 모든 필드에 업데이트 됨

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Frontend#550]
#### 문제 상황
쇼케이스 링크 수정 시 필드의 모든 값이 동시에 업데이트 됨
![S-SC 수정시 버그](https://github.com/peer-42seoul/Peer-Frontend/assets/91731260/64542693-e34d-40cf-945f-c21d72e9eaa4)

#### 테스트 환경

- OS(mac / ipad / android...) : 관련 없음
- 웹 브라우저 : 관련 없음

#### 사전 조건 (ex. 로그인 여부)
로그인 됨 (수정과 편집 연관 없음)

#### 재현 절차
링크 수정 필드에 칸을 추가하고 값을 입력합니다.

#### 예상 결과
(생략)

#### 실제 결과
다른 필드에도 값이 업데이트 됩니다.

#### 심각도
중

**Comment by asroq1** [comment]
새로 배포된 develop에서 pull 하시면 됩니다 ! 이슈 닫겠습니다.
