### ISSUE TITLE
[C-MYPAGE] 비밀번호 변경이 안됨

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#560]
#### 문제 상황

- 마이페이지에서 비밀번호 변경을 위해 버튼을 누르면 404 에러가 나옴
<img width="592" alt="image" src="https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/952209b6-9b19-40a7-97d8-5bddfa2217e2">

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 사전 조건 (ex. 로그인 여부)

로그인 O

#### 심각도

9 / 10

**Comment by SaltySalt77** [comment]
해당 api에서 로직이 변경된 상태라 비밀번호 변경이 불가능한 상태가 맞습니다
다음의 PR이 머지되면 비밀번호 변경이 가능해질 예정입니다. 
https://github.com/peer-42seoul/Peer-Frontend/pull/564
