### ISSUE TITLE
[BUG] 모집글 쓰기에서 역할 UI 무한정 늘어남

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#580]
#### 문제 상황

<img width="793" alt="스크린샷 2024-01-30 오후 8 06 05" src="https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/e3f63582-1407-48f7-b64d-a391a3432e86">

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 사전 조건 (ex. 로그인 여부)

- 로그인 필요
- 프로젝트 글 생성

#### 심각도

7 / 10

**Comment by SaltySalt77** [comment]
어제 리액트 훅 폼 연결하면서 수정 완료하였습니다.
