### ISSUE TITLE
[BUG / J-TB-15] 객관식 질문에 질문이 무제한으로 들어가는 버그 등등

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#589]
#### 문제 상황
1. 객관식 질문이 무제한으로 들어감: 다른 선택지 넣는 부분도 확인 필요
![스크린샷 2024-01-31 오후 3 51 33](https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/56e8f9af-6bc2-4ded-b8b3-b58a88f4ace2)

2. 객관식 질문의 선택지가 삭제가 안됨

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : safari

#### 사전 조건 (ex. 로그인 여부)

로그인 필요
모집글을 적는 중 인터뷰 등록

#### 심각도

9 / 10

**Comment by SaltySalt77** [comment]
최대 10개까지 가능한 것으로 알고있는데 10개보다도 더 많이 들어가나요....? @HiHoi

**Comment by SaltySalt77** [comment]
해결하여 이슈 닫습니다.
