### ISSUE TITLE
[BUG / H-SC] 쇼케이스 디테일 페이지에서 css 문제

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#605]
#### 문제 상황

<img width="919" alt="image" src="https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/0a087743-4f3e-4e18-9c18-ef8d9aa30021">

디테일 페이지에서 글자의 색상이 상반되지 않는 문제

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 심각도

9 / 10

**Comment by asroq1** [comment]
수정 하여서 PR 올렸습니다 !
