### ISSUE TITLE
[개선 요청] 모바일 하단 버튼 관련 수정요청

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/Peer-Frontend#606]
#### 문제 상황
![KakaoTalk_20240202_142703812_02](https://github.com/peer-42seoul/Peer-Frontend/assets/80471693/cd489dee-49f4-4614-a737-643b39aec0cb)
![KakaoTalk_20240202_142812850](https://github.com/peer-42seoul/Peer-Frontend/assets/80471693/5a3497d4-6e4a-4ebb-9572-a745836cec8b)

#### 테스트 환경

- OS(mac / ipad / android...) : iOS
- 웹 브라우저 : PWA, 사파리

#### 실제 결과
- 모바일을 기준으로 한다고 하지만, 버튼이 너무 낮습니다. 사파리만 보더라도 하단 UI 와 제스쳐 간섭을 최소화하고자 상당히 버튼이 위쪽에배치되지만 현재 저희 앱은 너무 아래로 내려가 있어, 아이폰의 제스쳐바와 겹치는 모습을 보여줍니다. 

#### 심각도
- 런칭전 반드시 개선 되어야함..!!

**Comment by HiHoi** [comment]
#646 해결 완료
