### ISSUE TITLE
[BUG] 모집글 작성 필수 요소 에러

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#647]
#### 문제 상황

- 이미지를 넣었음에도 불구하고 필수요소 요구가 뜸
<img width="541" alt="스크린샷 2024-02-04 오후 8 42 36" src="https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/1a4fe0a2-79cb-40ff-897c-a97d00062d06">

- 역할을 하나 넣었는데도 필수 요소 요구가 뜸
<img width="596" alt="스크린샷 2024-02-04 오후 8 42 55" src="https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/b6823d4c-4589-4219-8e76-db287195a4c4">

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 심각도

10 / 10

**Comment by SaltySalt77** [comment]
방금 해당 이슈 발견하여 수정중에 있습니다.
해당 이슈가 발생한 이유는 input 태그는 파일을 받고 있으나, value는 string이어서 발생한 문제였습니다.. 수동으로 setError를 돌리는 방안을 고려중입니다.
