### ISSUE TITLE
[C-MYPAGE] 닉네임 중복확인이 안됨

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#684]
#### 문제 상황
닉네임을 변경할때
한글 자음, 한글 모음, 공백이 들어있는 닉넹님으로 중복확인을 시도하면 아무런 알림이 오지않음.

response body
`{"messages":["nickname: 반드시, 영어, 한글, 숫자로만 닉네임을 설정해주셔야 합니다."]} `

백엔드에서 규격에 맞는 에러 문장으로 보내주지 않아서 프론트에서 인식을 못하고 잇음.

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by Paul2021-R** [comment]
수정 완료

**Comment by SaltySalt77** [comment]
처리 완료하였으므로 클로즈 처리합니다.
