### ISSUE TITLE
[H-SC] 쇼케이스 댓글 글자제한, 화면 벗어남

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#685]
#### 문제 상황
1. 쇼케이스 댓글에 글자제한이 안걸림 1000자 넘게도 작성이 됌.
2. 아래처럼 화면을 벗어남 쓰레기통 모양도 글자 맨 끝으로 밀려남

<img width="1166" alt="Screenshot 2024-02-05 at 5 23 03 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/7a5b6211-1c01-4a75-9796-95da2c613996">

#### 테스트 환경

- OS(mac / ipad / android...) : 맥
- 웹 브라우저 : 크롬

**Comment by asroq1** [comment]
해결하였습니다.
