### ISSUE TITLE
[C-MYPAGE] 새 쪽지 보내기에서 사용자 찾을때 한글 이름 검색이 안됨

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#691]
#### 문제 상황
새 쪽지 보내기 모달에서 사용자 검색중
한글이 들어가있으면 아래와같은 에러메세지가 발생함.
영어랑 같이 있어도 아래와 같은 에러가 뜸
<img width="601" alt="Screenshot 2024-02-05 at 5 28 34 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/6ebafb55-0f68-4df7-9074-431cfb1551d7">

#### 테스트 환경

- OS(mac / ipad / android...) : 맥
- 웹 브라우저 : 크롬

**Comment by Paul2021-R** [comment]
해결 완료 
프론트에서 오해를 부를 부분(이메일) 삭제 마무리 예정
