### ISSUE TITLE
[H-HITCH] 히치하이킹 되돌리기 

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#707]
#### 문제 상황
드래그로 모집글 되돌리기가 안됨.
그래서 드래그 말고 버튼으로만 누르게 된다.

#### 테스트 환경

- OS(mac / ipad /  android...) :맥
- 웹 브라우저 : 크롬

**Comment by SaltySalt77** [comment]
드래그로 모집글 되돌리기가 안된다는 뜻이 어떤 이야기일까요? 애초에 드래그로 히치하이킹 카드를 되돌리는 기능은 없습니다. @joonseong11

**Comment by joonseong11** [comment]
이부분은 이용자부분 피드백이예요, 위 버튼으로는 되돌리기가 되는데 드래그로는 되돌리기가 안되서 기능이 동작이 안되는 것 같다고 보인대요

**Comment by SaltySalt77** [comment]
이부분은 기획측과 이야기를 다시 해야할 것 같네요. 모바일에서 버튼이 없어서 추가해야한다는 이야기는 UX관점에서 모바일과 PC에서 같은 경험을 주는 게 옳다고 생각했기에 바로 반영하였습니다만, 기획과 관련된 부분이기도 하고 모든 것을 수용할 수는 없기 때문에 이부분은 논의 후 처리하면 좋겠습니다. 
기능상에 버그가 있는 것은 아니니 버그 레이블은 떼도록 하겠습니다.
피드백과 관련된 부분은 버그로 처리하지 말아주시길 부탁드립니다. @joonseong11

**Comment by SaltySalt77** [comment]
드래그로 히치하이킹 되돌리기가 추가되었습니다. 따라서 클로즈 처리합니다.
