### ISSUE TITLE
[D-TP] 관심리스트페이지에 "모집중"이 "모집완료"로 뜸

### ISSUE THREAD

**Issue by KRimwoo** [peer-42seoul/Peer-Frontend#729]
#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 실제 결과
<img width="498" alt="스크린샷 2024-02-05 오후 9 02 49" src="https://github.com/peer-42seoul/Peer-Frontend/assets/66295173/b82075b6-be3a-49db-87df-678a19dd5897">

Recruiting, Before, Ongoing, Complete 타입이 꼬인 것 같음

**Comment by SaltySalt77** [comment]
해결되어 클로즈 처리합니다.
