### ISSUE TITLE
[B-INFO] 비밀번호 찾기 이후, 비밀번호 변경이 안된다. 임시비밀번호에 기호가 없어서 접근불가

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#736]
#### 문제 상황
비밀번호를 까먹어서 비밀번호 찾기를 진행해 임시 비밀번호를 발급받았음.
jujeon42@gmail.com / kDMWnX0887
마이페이지-개인정보-비밀번호변경에서 현재 비밀번호를 입력하는 칸에서 막힘.
비밀번호에 특수문자가 포함되지 않았다고 다음으로 넘거가지지 않음.

<img width="571" alt="Screenshot 2024-02-05 at 10 32 01 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/caa7fb39-5a0d-468d-825b-325d41376538">

#### 테스트 환경

- OS(mac / ipad / android...) : 맥
- 웹 브라우저 : 크롬

**Comment by Paul2021-R** [comment]
- 임시 비밀번호에 대해 발급 시, 특수문자가 포함되지 않아, 비밀번호 변경이 안되는 문제 파악.
- 해당 API 로직에 특수문자를 집어넣는 로직 추가하여 마무리
