### ISSUE TITLE
[D-TP] 팀페이지 쇼케이스 페이지 새로고침시 탭메뉴 반영안됨 

### ISSUE THREAD

**Issue by KRimwoo** [peer-42seoul/Peer-Frontend#739]
#### 문제 상황
team/id/showcase 페이지에서 다른 페이지 이동 후 되돌아오거나 새로고침하면 메뉴탭이 다시 메인으로 선택된 것처럼 보임

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 실제 결과
<img width="1034" alt="스크린샷 2024-02-06 오전 10 08 18" src="https://github.com/peer-42seoul/Peer-Frontend/assets/66295173/6a308d98-07ed-4398-83dc-b90d19ef6e8c">

**Comment by yoouyeon** [comment]
@HiHoi 공통 네비게이션 바 부분 작업은 제가 했어서 이 문제는 제가 확인해볼게요!
