### ISSUE TITLE
[J-TB] 모집글 작성시 커뮤니케이션 링크 nullable 안됨

### ISSUE THREAD

**Issue by KRimwoo** [peer-42seoul/Peer-Frontend#742]
#### 문제 상황
모집글 작성에서 커뮤니케이션 링크 필수 입력사항 아닌 것으로 알고있는데 필수 입력칸으로 뜸
#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by SaltySalt77** [comment]
해결 된 이슈이므로 이슈 닫겠습니다~
