### ISSUE TITLE
[D-TP] 팀 리스트 모바일 디자인 보완

### ISSUE THREAD

**Issue by yoouyeon** [peer-42seoul/Peer-Frontend#756]
#### 문제 상황

팀 리스트의 팀 컴포넌트의 프로젝트 / 스터디 표시 디자인이 덜 입혀진 것 같아 보입니다.

<img width="30%" src="https://github.com/peer-42seoul/Peer-Frontend/assets/57761286/d92e7e8b-f977-4783-9107-4bd0fb284ce1" />
<img width="30%" src="https://github.com/peer-42seoul/Peer-Frontend/assets/57761286/397026f3-6ad8-4a3a-8b98-644f9068e09c" />

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by KRimwoo** [comment]
#851 에 수정 완료
