### ISSUE TITLE
[editor] 모집글, 게시판 등에서 화면이 어딘가 비어보인다. 토스트 에디터에 border를 적용하면 어떨까?

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#760]
#### 문제 상황
모집글
<img width="1019" alt="Screenshot 2024-02-06 at 1 55 30 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/81dd3241-de04-4f1c-9964-70df67ac146c">

팀페이지-게시판-게시글
<img width="947" alt="Screenshot 2024-02-06 at 1 55 15 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/49e42be0-6274-434c-9f3a-bf946f288952">

#### 테스트 환경

- OS(mac / ipad / android...) : 맥
- 웹 브라우저 : 크롬

**Comment by SaltySalt77** [comment]
해결하였으므로 클로즈 처리합니다.
