### ISSUE TITLE
[모집글] 커뮤니케이션 링크 필수?

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/Peer-Frontend#767]
#### 문제 상황
![image](https://github.com/peer-42seoul/Peer-Frontend/assets/80471693/450e44e8-1f12-4227-828a-d4645cc5f998)

원래 필수가 아니었으며
현재 URL 유효성 검사도 없기 때문에 그냥 아무값이나 들어감 

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by SaltySalt77** [comment]
해당 이슈 처리되어있고 CD 체크 중입니다 (테스트 서버에 해당 사항 반영이 안되어있었습니다...) 이슈 닫습니다.
