### ISSUE TITLE
[팀페이지] 팀게시판 사용 시 에러

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/Peer-Frontend#769]
#### 문제 상황
![스크린샷 2024-02-06 152946](https://github.com/peer-42seoul/Peer-Frontend/assets/80471693/0c99f19b-7be7-43f7-906f-f2b99d123334)

- 팀 페이지 게시판 최초 접속하여 게시판 관리를 누르면, 최초인데 데이터 없다고 에러를 나타내고 혼동을 야기함 

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 예상 결과

- 최초에는 당연히 게시판 관리로 들어가 작성이 가능해야 한다.

**Comment by yoouyeon** [comment]
로딩을 기다리지 못하고 데이터가 비어있는 경우에 우선적으로 데이터 로드 불가 에러 메시지를 띄우도록 해서 발생하던 문제였습니다. 로딩이 다 된 경우에만 빈 데이터를 확인하도록 로직을 수정했습니다.
