### ISSUE TITLE
[J-TB] 모집글 작성 시, 인터뷰 폼의 인터뷰 개수가 늘어나면 위의 내용이 잘림

### ISSUE THREAD

**Issue by hyeon81** [peer-42seoul/Peer-Frontend#786]
#### 문제 상황
![image](https://github.com/peer-42seoul/Peer-Frontend/assets/94117828/7b6f18ba-ab56-41e6-87db-986f687d06fe)
* 인터뷰 개수가 늘어나면 위의 인터뷰가 잘려서 스크롤이 올라가지 않습니다.

#### 테스트 환경

- OS(mac / ipad / android...) : WINDOW
- 웹 브라우저 : CHROME

**Comment by SaltySalt77** [comment]
해당사항 처리하였으므로 클로즈 처리합니다.
