### ISSUE TITLE
[ADMIN] 어드민 공지/배너 글을 볼때 이미지 업로드 버튼 누를 수 있음, 어드민 로그인 엔터로 로그인 

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#795]
#### 문제 상황
- 어드민 공지/배너 글을 볼때 이미지 업로드 버튼 누를 수 있음
- 어드민 공지 모달에서 위의 대표이미지가 절반이상 가려짐

#### 테스트 환경

- OS(mac / ipad / android...) :맥
- 웹 브라우저 : 크롬

**Comment by HiHoi** [comment]
@joonseong11 이 이슈 닫아도 되나요?
