### ISSUE TITLE
[BUG] 마이페이지 내 작업물 공개여부 ON 불가능

### ISSUE THREAD

**Issue by asroq1** [peer-42seoul/Peer-Frontend#801]
#### 문제 상황

https://github.com/peer-42seoul/Peer-Frontend/assets/62472550/1ce269cc-2687-4391-b8d6-82ed67bb4dd2

내 작업물 공개 여부 설정이 불가능 합니다.
#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by SaltySalt77** [comment]
백엔드에서 오타 수정되면 다시 테스트 해보고 머지하겠습니다~

**Comment by HiHoi** [comment]
@SaltySalt77 이거 닫아도 되나요?

**Comment by SaltySalt77** [comment]
테스트 완료되었으므로 닫겠습니다~
