### ISSUE TITLE
[toast editor] 토스트에디터로 글 내용 작성시 글자 한글기준 2000자 제한 필요

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#802]
#### 문제 상황
이전에 base64 기준이었을떄 글자제한을 걸 수 없었습니다.
이제는 변경되어 글자수 제한을 2000자로 제한하고자 합니다.

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by SaltySalt77** [comment]
2만자로 바꾸어달라는 요청이 와 클로즈 처리 합니다.
