### ISSUE TITLE
[1.0.1/모집게시글 작성] 모집게시글 작성시 태그에서 C, C++ 검색 안됨

### ISSUE THREAD

**Issue by weejihye** [peer-42seoul/Peer-Frontend#830]
#### 문제 상황
모집게시글 작성시 1글자 이상 검색, 특수문자 검색 제외 조건때문에
C와 C++ 태그를 검색할 수 없음(리스트에는 잘 들어가 있음)

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인
#### 재현 절차
모집게시글 작성 페이지에서 C 또는 C++로 태그 검색
#### 예상 결과
드롭다운에 태그가 검색되서 노출되어야 함.

#### 실제 결과
검색 불가

#### 심각도
4/10

**Comment by SaltySalt77** [comment]
원인 파악 후 백엔드와 논의중입니다~
