### ISSUE TITLE
[BUG / J-TB]  모집글 수정 -> 수정 완료 -> 다시 모집글 수정 시 수정전 데이터가 default value로 들어가있음

### ISSUE THREAD

**Issue by hyeon81** [peer-42seoul/Peer-Frontend#831]
#### 문제 상황
* 모집글 수정 -> 수정 완료 -> 다시 모집글 수정 시 이전 데이터가 들어감
* 모집글을 수정한 뒤 다시 모집글을 수정하면 방금 수정한 데이터가 아니라 수정전에 데이터가 default data로 들어감

#### 테스트 환경

- OS(mac / ipad / android...) : window
- 웹 브라우저 : 크롬

#### 심각도
7/10

**Comment by SaltySalt77** [comment]
확인했습니다~
