### ISSUE TITLE
[1.0.2 / 히치하이킹] UI 짤림 현상

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#844]
#### 문제 상황

![image](https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/84dac3ae-3b32-41ea-a0da-ad13a7792923)

모바일 버전에서 아래 하트 버튼이 짤림

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by SaltySalt77** [comment]
지금 카드 사이즈 기준이 모바일은 가로, pc는 세로로 되어있는데, 모바일도 세로로 바꾸겠습니다~
