### ISSUE TITLE
[쇼케이스 + 히치하이킹] UX 개선점

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#846]
#### 구현 필수 목록

- [ ] 카드의 위치와 사용자가 스와이프 하는 영역의 차이점이 큼
- [ ] 카드의 사이즈를 키우거나 위치를 내려야 하는 상황

**Comment by SaltySalt77** [comment]
### 고려중인 변경 사항
1. 히치하이킹도 카드를 아래로 내린다.
2. 아래로 내리는 것만 아니면 일단 다 카드 넘기는 것으로 처리한다.
3. 히치하이킹도 하트를 카드 안에 넣어버린다.
등등등....

**Comment by SaltySalt77** [comment]
1.0.4에 정상 반영되었습니다. 따라서 close 처리합니다.
