### ISSUE TITLE
[J-TB] 모집글을 쓸 때 기술 스택 부분을 필수 요소에서 제외하기

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#890]
#### 구현 필수 목록

- [ ] 기획자 입장에서 어떤 기술 스택이 필요한지 모르는 상황일 때를 고려

**Comment by SaltySalt77** [comment]
이부분은 버그가 아닌 유저 피드백이므로 기존 담당자의 판단이 중요하다 여겨 @joonseong11님 배정해둡니다.
