### ISSUE TITLE
[BUG / 마이페이지] 소개 수정에서 닉네임 수정 이슈

### ISSUE THREAD

**Issue by asroq1** [peer-42seoul/Peer-Frontend#897]
#### 문제 상황
닉네임 수정에 특수문자가 들어가면 수정이 안 됩니다. 백엔드에서 주는 에러 메시지랑 프론트 토스트에서 주는 에러 메시지가 달라요.
<img width="1212" alt="Screenshot 2024-02-08 at 5 00 38 PM" src="https://github.com/peer-42seoul/Peer-Frontend/assets/62472550/f9f3cdc3-bbc6-4fbd-9be2-cdbae1f8fbbd">

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by SaltySalt77** [comment]
프론트 에러메세지 처리 확인해보겠습니다.
또한 백엔드 담당자에게도 정해진 형식에 맞게 리스폰스를 달라고 요청했습니다.

**Comment by SaltySalt77** [comment]
백엔드에 수정 요청 넣었습니다. 백엔드 작업 이후 다시 확인 요망

**Comment by SaltySalt77** [comment]
백엔드에서 처리 불가능하다는 답변 받음. 형식 바꾸어야함
