### ISSUE TITLE
[1.0.3 / PUBLIC] accessToken의 만료

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Frontend#914]
#### 문제 상황

<img width="1138" alt="스크린샷 2024-02-11 오후 2 23 45" src="https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/b7a904fb-22a0-4bfc-840e-0f1deccde4d0">

아마 쿠키에 담긴 accessToken이 계속 남아있는 거 같습니다. 기존에 알고 있던 거랑 다르게 세션 쿠키가 작동하는 거 같으니 확인 부탁드립니다.

<img width="825" alt="image" src="https://github.com/peer-42seoul/Peer-Frontend/assets/54823522/ccdadb2a-a8df-43d5-b232-a6f59707622e">

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by HiHoi** [comment]
출처 https://velog.io/@software/세션-쿠키와-지속-쿠키

**Comment by HiHoi** [comment]
아마 이 문제때문에 가끔 페이지에 들어왔을 때 401 에러가 보이는 문제가 생기는 거 같습니다.
그 이유로는 서버에서 제공한 accessToken의 만료가 지났음에도 SSR 시 이전 로그인 때 발급한 만료된 Token이 쿠키에 있어서 그 token를 갖고 접근하면서 서버에서는 다시 로그인을 하라는 401를 보내는 거 같습니다.

**Comment by KRimwoo** [comment]
토큰이 만료되면 reissue 후 로그아웃 처리를 하는데 그 로그아웃 과정이 일반 로그아웃(api요청 보냄)과 분리되어있지 않아 생기는 문제 같습니다! 쿠키 세팅부분도 같이 지우면서 처리해볼게요
