### ISSUE TITLE
[PUBLIC] CuNavbar 팀페이지-쇼케이스 탭에서 new 글자가 색이 반영이 안됨

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Frontend#945]
#### 문제 상황
피그마 기준 팀페이지에서 '쇼케이스 new' 여기 부분에 new는 yellow.strong 로 적용이 되어야 하는데, 흰색으로 적용되어있음

피그마 | 구현된 페이지
---|---
<img width="378" alt="스크린샷 2024-02-13 오후 10 56 40" src="https://github.com/peer-42seoul/Peer-Frontend/assets/91731260/d611b614-3bcd-47d1-8991-9f742ef5c183">|<img width="378" src="https://github.com/peer-42seoul/Peer-Frontend/assets/87654307/a6939ea1-0ba1-4457-b964-da4e5d3cf09d" />

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by SaltySalt77** [comment]
@yoouyeon CuNavbar 혹시 건드리고 계신다면 이 버그 수정 부탁드려도 될까요?

**Comment by yoouyeon** [comment]
@SaltySalt77 넵 그쪽 작업하고있었어요 같이 수정할게요!
