### ISSUE TITLE
[1.0.3 / D-TP] 팀 페이지 모바일 레이아웃 버그

### ISSUE THREAD

**Issue by yoouyeon** [peer-42seoul/Peer-Frontend#954]
#### 문제 상황

기존 디자인에 비해 팀 게시판 페이지는 좁아지고, 팀 설정 페이지는 화면을 벗어나는 문제가 있습니다.
<img width="30%" src="https://github.com/peer-42seoul/Peer-Frontend/assets/57761286/e4c67162-96e1-429b-a9f1-7c0691d9ff8c" /> <img width="30%" src="https://github.com/peer-42seoul/Peer-Frontend/assets/57761286/c4371d13-5831-42d7-a9d7-8714460d8857" />

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by KRimwoo** [comment]
이거 지금 제가 고치고 있습니당!
